### ISSUE TITLE
Missing conda environment.yml file

### ISSUE THREAD

**Issue by fhorvat** [BIMSBbioinfo/pigx_rnaseq#53]
I tried to install pipeline though Conda using provided instuctions, but the enviornment.yml file is missing from git repo

**Comment by borauyar** [comment]
Hi @fhorvat. Sorry for the late response. Actually, you are misguided by our documentation as I was supposed to remove the section about how to install the pipeline via Conda. 
We highly recommend using Guix if possible. Otherwise, it might be better to use the 'requirements.txt' file to create a new environment with the dependencies of the pipeline. However, we may not be able to provide much support on the Conda related issues.

**Comment by borauyar** [comment]
https://github.com/BIMSBbioinfo/pigx_rnaseq/commit/7d211c9f24af840adec9f9fe07150790e008e65f
