### ISSUE TITLE
remove files from distribution that are created/changed/cleaned during/after build

### ISSUE THREAD

**Issue by smoe** [BIMSBbioinfo/pigx_rnaseq#66]
Please remove files created/modified during build or that are "make clean"ed. To mind come
```
	deleted:    Makefile.in
	deleted:    build-aux/missing
	deleted:    build-aux/test-driver
```
Cheers,
Steffen

**Comment by borauyar** [comment]
@rekado doesn't this fix this issue?https://github.com/BIMSBbioinfo/pigx_rnaseq/commit/8a07578ee4dc28a193345144e86a4cd24f723357
Makefile.in and build-aux/* are in .gitignore. However these files all end up in the tarball as a result of `make distcheck`. Do you know how to avoid this (if they need to be excluded at all)?

**Comment by rekado** [comment]
It is correct that they end up in the *tarball*.  But they should not be tracked in the *repository*.

`make dist`(check) produces a "bootstrapped" tarball.  The idea behind autotools is that *users* don't need to have autotools (or m4, or automake, etc); they just need a POSIX-compliant shell.  That's why the generated tarballs contain a "compiled" `configure` shell script, an instantiated `Makefile.in` (from the automake source file `Makefile.am`), and so on.

I haven't looked very carefully, but your commit seems to be sufficient to close this issue.

**Comment by borauyar** [comment]
Okay, thank you. It was your commit, though :)

**Comment by rekado** [comment]
Oof, that shows just *how* carefully I looked :)
